In [1]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df= pd.read_csv ("C:\DSBDA\Practicals\Pandas\Boston housing.csv")

In [6]:
df

        RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]

In [7]:
df.info

<bound method DataFrame.info of         RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]>

In [8]:
df.shape

(489, 4)

In [9]:
df.columns

Index(['RM', 'LSTAT', 'PTRATIO', 'MEDV'], dtype='object')

In [11]:
df.describe()

               RM       LSTAT     PTRATIO          MEDV
count  489.000000  489.000000  489.000000  4.890000e+02
mean     6.240288   12.939632   18.516564  4.543429e+05
std      0.643650    7.081990    2.111268  1.653403e+05
min      3.561000    1.980000   12.600000  1.050000e+05
25%      5.880000    7.370000   17.400000  3.507000e+05
50%      6.185000   11.690000   19.100000  4.389000e+05
75%      6.575000   17.120000   20.200000  5.187000e+05
max      8.398000   37.970000   22.000000  1.024800e+06

In [12]:
df.isnull().sum()

RM         0
LSTAT      0
PTRATIO    0
MEDV       0
dtype: int64

In [13]:
df = df.fillna(df.mean())

In [15]:
X = df.drop("MEDV", axis=1)
y = df["MEDV"]
df

        RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [29]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

In [30]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [31]:
mse = mean_squared_error(y_test, y_test_pred)
print("MSE:", mse)

MSE: 6789025559.265894

In [32]:
rmse = np.sqrt(mse)
print("RMSE:", rmse)

RMSE: 82395.54332162568

In [33]:
y_mean = np.mean(y_test)
y_mean

np.float64(424757.14285714284)

In [34]:
SSE = np.sum((y_test - y_test_pred)**2)
print("SSE:", SSE)

SSE: 665324504808.0576

In [35]:
SST = np.sum((y_test - y_mean)**2)
print("SST:", SST)

SST: 2153804760000.0002

In [36]:
SSR = SST - SSE
print("SSR:", SSR)

SSR: 1488480255191.9426

In [37]:
r2_manual = SSR / SST
print("Manual R2:", r2_manual)

Manual R2: 0.691093400309851

In [ ]:
plt.scatter(y_test, y_test_pred)
plt.xlabel("True Values")
plt.ylabel("Predicted Values")
plt.title("True vs Predicted House Prices")
plt.show()

In [28]:
plt.scatter(y_train, ytrain_pred,c='blue',marker='o',label='Training data')
plt.scatter(y_test, ytest_pred,c='red',marker='s',label='Test data')
plt.xlabel('True values')
plt.ylabel('Predicted')
plt.title("True value vs Predicted value")
plt.legend(loc='upper left')
plt.plot()
plt.show()

NameError: name 'ytrain_pred' is not defined